[globals]
platform =  espressif32@6.10.0
framework = espidf
check_tool = clangtidy
build_flags =
	-std=gnu++20
	-Wno-unknown-pragmas ; https://stackoverflow.com/questions/12894454/how-to-remove-gcc-warning-on-pragma-region
	-Wno-missing-field-initializers
	-DCONFIG_NIMBLE_CPP_IDF=1 ; https://github.com/h2zero/esp-nimble-cpp/issues/407
build_unflags =
	-std=gnu++11
	-fno-rtti ; Enables runtime type information, which is required for C++ features like dynamic_cast and typeid.
monitor_raw = yes
monitor_speed = 115200
lib_deps =
	bblanchon/ArduinoJson@^7.2.1
	h2zero/esp-nimble-cpp@^2.4.0

[release]
extends = globals
build_type = release
build_flags =
	${globals.build_flags}
	-DCORE_DEBUG_LEVEL=1
	-O2

[debug]
extends = globals
build_type = debug
lib_extra_dirs = components
test_framework = unity
monitor_speed = 230400
test_speed = 115200
debug_init_break = break setup
build_flags =
	${globals.build_flags}
	-Wno-unused-variable
	-DCORE_DEBUG_LEVEL=5 ; https://community.platformio.org/t/how-to-set-up-log-level-to-be-able-to-debug-the-esp32/8278
	-D DEBUG_LOG_LEVEL=ESP_LOG_DEBUG
	-D DEBUG
	; https://github.com/espressif/openocd-esp32/issues/246
	-O0 ; Same as -D CONFIG_COMPILER_OPTIMIZATION_NONE
	-g

[env:esp32_c6]
extends = release
board = esp32-c6-devkitm-1
board_build.partitions = c6_partition_table.csv
board_build.flash_size = 4MB

[env:esp32_c6_dev]
extends = env:esp32_c6, debug
debug_tool = esp-builtin
debug_server =
	${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
	-f
	${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts/board/esp32c6-builtin.cfg
